%YAML 1.1
---

rgb_high_topic: "/camera/high/image_raw"
rgb_left_topic: "/camera/left_wrist/image_raw"
rgb_right_topic: "/camera/right_wrist/image_raw"
left_joint_states_topic: "/left_arm/joint_states"
right_joint_states_topic: "/right_arm/joint_states"
path_to_save: ""
camera_fps: 30
